### ISSUE TITLE
SECURITY.md is missing

### ISSUE THREAD

**Issue by eslerm** [OpenPrinting/fuzzing#3]
Please add a SECURITY.md file as a security policy.

The content is in the README.md, but it's a better practice to have a separate document (even if it is duplicate info).

**Comment by iosifache** [comment]
I will argue that this is not required.

The purpose of `SECURITY.md` is to highlight how the OSS project/organisation prefers to have the issues from the codebases they are storing reported.

I didn't check all OpenPrinting repositories, but some of them (for example, [`cups`](https://github.com/OpenPrinting/cups/blob/master/SECURITY.md)) already have a security policy in place. This is a separate discussion.

In the context of this repository, the section that you are referencing describes how the issues discovered with the embedded harnesses should not be reported in GitHub issues. IMO, a `SECURITY.md` in the context of this repository will guide the security researchers on how they can report security issue in the harness themselves (which will be Inception-like, but not the case here).

**Comment by eslerm** [comment]
> The purpose of `SECURITY.md` is to highlight how the OSS project/organisation prefers to have the issues from the codebases they are storing reported.

Agreed. That's why I thought info in https://github.com/OpenPrinting/fuzzing?tab=readme-ov-file#bug-reporting could be moved or duplicated in a SECURITY.md.

> I didn't check all OpenPrinting repositories, but some of them (for example, [`cups`](https://github.com/OpenPrinting/cups/blob/master/SECURITY.md)) already have a security policy in place. This is a separate discussion.

It would be really cool if they all had them with GitHub Private Security Reporting \o/

> In the context of this repository, the section that you are referencing describes how the issues discovered with the embedded harnesses should not be reported in GitHub issues. IMO, a `SECURITY.md` in the context of this repository will guide the security researchers on how they can report security issue in the harness themselves (which will be Inception-like, but not the case here).

Yeah, it is unlikely that this info is needed *for the harness* (any real issues are likely in oss-fuzz or other upstream). But the SECURITY.md may still be checked by fuzzing researchers and it's useful to have (like it is in the README.md). Security Policy info can apply to the whole org generally in addition to a specific project.

Please feel free to close this if needed. I don't mean to bike shed :pray:
